package com.tew.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.PER_CHECK
 *
 * @mbg.generated do_not_delete_during_merge 2019-11-09 22:33:41
 */
public class Check implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.ID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.THEMEID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_INFO
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_WISH
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialWish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_RES
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialRes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_NET
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_MONEY
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_M
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_W
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_I
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialI;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_H
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_P
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_E
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.WRITE_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private BigDecimal writeExam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.INTER_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private BigDecimal interExam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.SCORE
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.CREATE_AT
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_CHECK.TRIAL_G
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private Short trialG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.PER_CHECK
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.ID
     *
     * @return the value of SYS.PER_CHECK.ID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.ID
     *
     * @param id the value for SYS.PER_CHECK.ID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.THEMEID
     *
     * @return the value of SYS.PER_CHECK.THEMEID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.THEMEID
     *
     * @param themeid the value for SYS.PER_CHECK.THEMEID
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setThemeid(Short themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_INFO
     *
     * @return the value of SYS.PER_CHECK.TRIAL_INFO
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialInfo() {
        return trialInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_INFO
     *
     * @param trialInfo the value for SYS.PER_CHECK.TRIAL_INFO
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialInfo(Short trialInfo) {
        this.trialInfo = trialInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_WISH
     *
     * @return the value of SYS.PER_CHECK.TRIAL_WISH
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialWish() {
        return trialWish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_WISH
     *
     * @param trialWish the value for SYS.PER_CHECK.TRIAL_WISH
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialWish(Short trialWish) {
        this.trialWish = trialWish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_RES
     *
     * @return the value of SYS.PER_CHECK.TRIAL_RES
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialRes() {
        return trialRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_RES
     *
     * @param trialRes the value for SYS.PER_CHECK.TRIAL_RES
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialRes(Short trialRes) {
        this.trialRes = trialRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_NET
     *
     * @return the value of SYS.PER_CHECK.TRIAL_NET
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialNet() {
        return trialNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_NET
     *
     * @param trialNet the value for SYS.PER_CHECK.TRIAL_NET
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialNet(Short trialNet) {
        this.trialNet = trialNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_MONEY
     *
     * @return the value of SYS.PER_CHECK.TRIAL_MONEY
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialMoney() {
        return trialMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_MONEY
     *
     * @param trialMoney the value for SYS.PER_CHECK.TRIAL_MONEY
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialMoney(Short trialMoney) {
        this.trialMoney = trialMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_M
     *
     * @return the value of SYS.PER_CHECK.TRIAL_M
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialM() {
        return trialM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_M
     *
     * @param trialM the value for SYS.PER_CHECK.TRIAL_M
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialM(Short trialM) {
        this.trialM = trialM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_W
     *
     * @return the value of SYS.PER_CHECK.TRIAL_W
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialW() {
        return trialW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_W
     *
     * @param trialW the value for SYS.PER_CHECK.TRIAL_W
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialW(Short trialW) {
        this.trialW = trialW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_I
     *
     * @return the value of SYS.PER_CHECK.TRIAL_I
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialI() {
        return trialI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_I
     *
     * @param trialI the value for SYS.PER_CHECK.TRIAL_I
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialI(Short trialI) {
        this.trialI = trialI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_H
     *
     * @return the value of SYS.PER_CHECK.TRIAL_H
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialH() {
        return trialH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_H
     *
     * @param trialH the value for SYS.PER_CHECK.TRIAL_H
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialH(Short trialH) {
        this.trialH = trialH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_P
     *
     * @return the value of SYS.PER_CHECK.TRIAL_P
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialP() {
        return trialP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_P
     *
     * @param trialP the value for SYS.PER_CHECK.TRIAL_P
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialP(Short trialP) {
        this.trialP = trialP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_E
     *
     * @return the value of SYS.PER_CHECK.TRIAL_E
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialE() {
        return trialE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_E
     *
     * @param trialE the value for SYS.PER_CHECK.TRIAL_E
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialE(Short trialE) {
        this.trialE = trialE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.WRITE_EXAM
     *
     * @return the value of SYS.PER_CHECK.WRITE_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public BigDecimal getWriteExam() {
        return writeExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.WRITE_EXAM
     *
     * @param writeExam the value for SYS.PER_CHECK.WRITE_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setWriteExam(BigDecimal writeExam) {
        this.writeExam = writeExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.INTER_EXAM
     *
     * @return the value of SYS.PER_CHECK.INTER_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public BigDecimal getInterExam() {
        return interExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.INTER_EXAM
     *
     * @param interExam the value for SYS.PER_CHECK.INTER_EXAM
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setInterExam(BigDecimal interExam) {
        this.interExam = interExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.SCORE
     *
     * @return the value of SYS.PER_CHECK.SCORE
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.SCORE
     *
     * @param score the value for SYS.PER_CHECK.SCORE
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.CREATE_AT
     *
     * @return the value of SYS.PER_CHECK.CREATE_AT
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.CREATE_AT
     *
     * @param createAt the value for SYS.PER_CHECK.CREATE_AT
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_CHECK.TRIAL_G
     *
     * @return the value of SYS.PER_CHECK.TRIAL_G
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public Short getTrialG() {
        return trialG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_CHECK.TRIAL_G
     *
     * @param trialG the value for SYS.PER_CHECK.TRIAL_G
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    public void setTrialG(Short trialG) {
        this.trialG = trialG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_CHECK
     *
     * @mbg.generated 2019-11-09 22:33:41
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", themeid=").append(themeid);
        sb.append(", trialInfo=").append(trialInfo);
        sb.append(", trialWish=").append(trialWish);
        sb.append(", trialRes=").append(trialRes);
        sb.append(", trialNet=").append(trialNet);
        sb.append(", trialMoney=").append(trialMoney);
        sb.append(", trialM=").append(trialM);
        sb.append(", trialW=").append(trialW);
        sb.append(", trialI=").append(trialI);
        sb.append(", trialH=").append(trialH);
        sb.append(", trialP=").append(trialP);
        sb.append(", trialE=").append(trialE);
        sb.append(", writeExam=").append(writeExam);
        sb.append(", interExam=").append(interExam);
        sb.append(", score=").append(score);
        sb.append(", createAt=").append(createAt);
        sb.append(", trialG=").append(trialG);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}