package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.WISH_INFO
 *
 * @mbg.generated do_not_delete_during_merge 2019-08-31 09:33:07
 */
public class Wish implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.WISHID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Short wishid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.SCHOOLID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Short schoolid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.POST
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.POSTID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Short postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.CREATE_AT
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.WISH_INFO.THEMEID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Short themeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.WISH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.WISHID
     *
     * @return the value of SYS.WISH_INFO.WISHID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Short getWishid() {
        return wishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.WISHID
     *
     * @param wishid the value for SYS.WISH_INFO.WISHID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setWishid(Short wishid) {
        this.wishid = wishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.ID
     *
     * @return the value of SYS.WISH_INFO.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.ID
     *
     * @param id the value for SYS.WISH_INFO.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.SCHOOL_NAME
     *
     * @return the value of SYS.WISH_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.SCHOOL_NAME
     *
     * @param schoolName the value for SYS.WISH_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.SCHOOLID
     *
     * @return the value of SYS.WISH_INFO.SCHOOLID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Short getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.SCHOOLID
     *
     * @param schoolid the value for SYS.WISH_INFO.SCHOOLID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setSchoolid(Short schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.POST
     *
     * @return the value of SYS.WISH_INFO.POST
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.POST
     *
     * @param post the value for SYS.WISH_INFO.POST
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.POSTID
     *
     * @return the value of SYS.WISH_INFO.POSTID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Short getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.POSTID
     *
     * @param postid the value for SYS.WISH_INFO.POSTID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setPostid(Short postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.CREATE_AT
     *
     * @return the value of SYS.WISH_INFO.CREATE_AT
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.CREATE_AT
     *
     * @param createAt the value for SYS.WISH_INFO.CREATE_AT
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.WISH_INFO.THEMEID
     *
     * @return the value of SYS.WISH_INFO.THEMEID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Short getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.WISH_INFO.THEMEID
     *
     * @param themeid the value for SYS.WISH_INFO.THEMEID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setThemeid(Short themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.WISH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wishid=").append(wishid);
        sb.append(", id=").append(id);
        sb.append(", schoolName=").append(schoolName);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", post=").append(post);
        sb.append(", postid=").append(postid);
        sb.append(", createAt=").append(createAt);
        sb.append(", themeid=").append(themeid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}