package com.tew.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public JobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostidIsNull() {
            addCriterion("POSTID is null");
            return (Criteria) this;
        }

        public Criteria andPostidIsNotNull() {
            addCriterion("POSTID is not null");
            return (Criteria) this;
        }

        public Criteria andPostidEqualTo(Short value) {
            addCriterion("POSTID =", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotEqualTo(Short value) {
            addCriterion("POSTID <>", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidGreaterThan(Short value) {
            addCriterion("POSTID >", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidGreaterThanOrEqualTo(Short value) {
            addCriterion("POSTID >=", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidLessThan(Short value) {
            addCriterion("POSTID <", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidLessThanOrEqualTo(Short value) {
            addCriterion("POSTID <=", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidIn(List<Short> values) {
            addCriterion("POSTID in", values, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotIn(List<Short> values) {
            addCriterion("POSTID not in", values, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidBetween(Short value1, Short value2) {
            addCriterion("POSTID between", value1, value2, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotBetween(Short value1, Short value2) {
            addCriterion("POSTID not between", value1, value2, "postid");
            return (Criteria) this;
        }

        public Criteria andThemeidIsNull() {
            addCriterion("THEMEID is null");
            return (Criteria) this;
        }

        public Criteria andThemeidIsNotNull() {
            addCriterion("THEMEID is not null");
            return (Criteria) this;
        }

        public Criteria andThemeidEqualTo(Short value) {
            addCriterion("THEMEID =", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidNotEqualTo(Short value) {
            addCriterion("THEMEID <>", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidGreaterThan(Short value) {
            addCriterion("THEMEID >", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidGreaterThanOrEqualTo(Short value) {
            addCriterion("THEMEID >=", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidLessThan(Short value) {
            addCriterion("THEMEID <", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidLessThanOrEqualTo(Short value) {
            addCriterion("THEMEID <=", value, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidIn(List<Short> values) {
            addCriterion("THEMEID in", values, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidNotIn(List<Short> values) {
            addCriterion("THEMEID not in", values, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidBetween(Short value1, Short value2) {
            addCriterion("THEMEID between", value1, value2, "themeid");
            return (Criteria) this;
        }

        public Criteria andThemeidNotBetween(Short value1, Short value2) {
            addCriterion("THEMEID not between", value1, value2, "themeid");
            return (Criteria) this;
        }

        public Criteria andPostIsNull() {
            addCriterion("POST is null");
            return (Criteria) this;
        }

        public Criteria andPostIsNotNull() {
            addCriterion("POST is not null");
            return (Criteria) this;
        }

        public Criteria andPostEqualTo(String value) {
            addCriterion("POST =", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotEqualTo(String value) {
            addCriterion("POST <>", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThan(String value) {
            addCriterion("POST >", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThanOrEqualTo(String value) {
            addCriterion("POST >=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThan(String value) {
            addCriterion("POST <", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThanOrEqualTo(String value) {
            addCriterion("POST <=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLike(String value) {
            addCriterion("POST like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotLike(String value) {
            addCriterion("POST not like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostIn(List<String> values) {
            addCriterion("POST in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotIn(List<String> values) {
            addCriterion("POST not in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostBetween(String value1, String value2) {
            addCriterion("POST between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotBetween(String value1, String value2) {
            addCriterion("POST not between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("NUM is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("NUM is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Short value) {
            addCriterion("NUM =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Short value) {
            addCriterion("NUM <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Short value) {
            addCriterion("NUM >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Short value) {
            addCriterion("NUM >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Short value) {
            addCriterion("NUM <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Short value) {
            addCriterion("NUM <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Short> values) {
            addCriterion("NUM in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Short> values) {
            addCriterion("NUM not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Short value1, Short value2) {
            addCriterion("NUM between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Short value1, Short value2) {
            addCriterion("NUM not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("CREATE_AT is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("CREATE_AT is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("CREATE_AT =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("CREATE_AT <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("CREATE_AT >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_AT >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("CREATE_AT <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_AT <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("CREATE_AT in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("CREATE_AT not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("CREATE_AT between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_AT not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andWriteExamIsNull() {
            addCriterion("WRITE_EXAM is null");
            return (Criteria) this;
        }

        public Criteria andWriteExamIsNotNull() {
            addCriterion("WRITE_EXAM is not null");
            return (Criteria) this;
        }

        public Criteria andWriteExamEqualTo(BigDecimal value) {
            addCriterion("WRITE_EXAM =", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamNotEqualTo(BigDecimal value) {
            addCriterion("WRITE_EXAM <>", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamGreaterThan(BigDecimal value) {
            addCriterion("WRITE_EXAM >", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("WRITE_EXAM >=", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamLessThan(BigDecimal value) {
            addCriterion("WRITE_EXAM <", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamLessThanOrEqualTo(BigDecimal value) {
            addCriterion("WRITE_EXAM <=", value, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamIn(List<BigDecimal> values) {
            addCriterion("WRITE_EXAM in", values, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamNotIn(List<BigDecimal> values) {
            addCriterion("WRITE_EXAM not in", values, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WRITE_EXAM between", value1, value2, "writeExam");
            return (Criteria) this;
        }

        public Criteria andWriteExamNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WRITE_EXAM not between", value1, value2, "writeExam");
            return (Criteria) this;
        }

        public Criteria andInterExamIsNull() {
            addCriterion("INTER_EXAM is null");
            return (Criteria) this;
        }

        public Criteria andInterExamIsNotNull() {
            addCriterion("INTER_EXAM is not null");
            return (Criteria) this;
        }

        public Criteria andInterExamEqualTo(BigDecimal value) {
            addCriterion("INTER_EXAM =", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamNotEqualTo(BigDecimal value) {
            addCriterion("INTER_EXAM <>", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamGreaterThan(BigDecimal value) {
            addCriterion("INTER_EXAM >", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTER_EXAM >=", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamLessThan(BigDecimal value) {
            addCriterion("INTER_EXAM <", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTER_EXAM <=", value, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamIn(List<BigDecimal> values) {
            addCriterion("INTER_EXAM in", values, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamNotIn(List<BigDecimal> values) {
            addCriterion("INTER_EXAM not in", values, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTER_EXAM between", value1, value2, "interExam");
            return (Criteria) this;
        }

        public Criteria andInterExamNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTER_EXAM not between", value1, value2, "interExam");
            return (Criteria) this;
        }

        public Criteria andSchoolinIsNull() {
            addCriterion("SCHOOLIN is null");
            return (Criteria) this;
        }

        public Criteria andSchoolinIsNotNull() {
            addCriterion("SCHOOLIN is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolinEqualTo(String value) {
            addCriterion("SCHOOLIN =", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinNotEqualTo(String value) {
            addCriterion("SCHOOLIN <>", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinGreaterThan(String value) {
            addCriterion("SCHOOLIN >", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinGreaterThanOrEqualTo(String value) {
            addCriterion("SCHOOLIN >=", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinLessThan(String value) {
            addCriterion("SCHOOLIN <", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinLessThanOrEqualTo(String value) {
            addCriterion("SCHOOLIN <=", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinLike(String value) {
            addCriterion("SCHOOLIN like", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinNotLike(String value) {
            addCriterion("SCHOOLIN not like", value, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinIn(List<String> values) {
            addCriterion("SCHOOLIN in", values, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinNotIn(List<String> values) {
            addCriterion("SCHOOLIN not in", values, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinBetween(String value1, String value2) {
            addCriterion("SCHOOLIN between", value1, value2, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinNotBetween(String value1, String value2) {
            addCriterion("SCHOOLIN not between", value1, value2, "schoolin");
            return (Criteria) this;
        }

        public Criteria andSchoolinidIsNull() {
            addCriterion("SCHOOLINID is null");
            return (Criteria) this;
        }

        public Criteria andSchoolinidIsNotNull() {
            addCriterion("SCHOOLINID is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolinidEqualTo(String value) {
            addCriterion("SCHOOLINID =", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidNotEqualTo(String value) {
            addCriterion("SCHOOLINID <>", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidGreaterThan(String value) {
            addCriterion("SCHOOLINID >", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidGreaterThanOrEqualTo(String value) {
            addCriterion("SCHOOLINID >=", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidLessThan(String value) {
            addCriterion("SCHOOLINID <", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidLessThanOrEqualTo(String value) {
            addCriterion("SCHOOLINID <=", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidLike(String value) {
            addCriterion("SCHOOLINID like", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidNotLike(String value) {
            addCriterion("SCHOOLINID not like", value, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidIn(List<String> values) {
            addCriterion("SCHOOLINID in", values, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidNotIn(List<String> values) {
            addCriterion("SCHOOLINID not in", values, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidBetween(String value1, String value2) {
            addCriterion("SCHOOLINID between", value1, value2, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andSchoolinidNotBetween(String value1, String value2) {
            addCriterion("SCHOOLINID not between", value1, value2, "schoolinid");
            return (Criteria) this;
        }

        public Criteria andClazzIsNull() {
            addCriterion("CLAZZ is null");
            return (Criteria) this;
        }

        public Criteria andClazzIsNotNull() {
            addCriterion("CLAZZ is not null");
            return (Criteria) this;
        }

        public Criteria andClazzEqualTo(String value) {
            addCriterion("CLAZZ =", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzNotEqualTo(String value) {
            addCriterion("CLAZZ <>", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzGreaterThan(String value) {
            addCriterion("CLAZZ >", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzGreaterThanOrEqualTo(String value) {
            addCriterion("CLAZZ >=", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzLessThan(String value) {
            addCriterion("CLAZZ <", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzLessThanOrEqualTo(String value) {
            addCriterion("CLAZZ <=", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzLike(String value) {
            addCriterion("CLAZZ like", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzNotLike(String value) {
            addCriterion("CLAZZ not like", value, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzIn(List<String> values) {
            addCriterion("CLAZZ in", values, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzNotIn(List<String> values) {
            addCriterion("CLAZZ not in", values, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzBetween(String value1, String value2) {
            addCriterion("CLAZZ between", value1, value2, "clazz");
            return (Criteria) this;
        }

        public Criteria andClazzNotBetween(String value1, String value2) {
            addCriterion("CLAZZ not between", value1, value2, "clazz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated do_not_delete_during_merge 2019-08-31 09:33:07
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.INV_JOB
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}