package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.ACC_PERMISS
 *
 * @mbg.generated do_not_delete_during_merge 2019-11-04 15:38:42
 */
public class Permiss implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.POWERID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private Short powerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.ID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.DESCRIPTION
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.DBPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private String dbpermiss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.FCPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private String fcpermiss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.GET_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private Date getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.END_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.ENABLE
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private Short enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ACC_PERMISS.PID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.POWERID
     *
     * @return the value of SYS.ACC_PERMISS.POWERID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public Short getPowerid() {
        return powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.POWERID
     *
     * @param powerid the value for SYS.ACC_PERMISS.POWERID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setPowerid(Short powerid) {
        this.powerid = powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.ID
     *
     * @return the value of SYS.ACC_PERMISS.ID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.ID
     *
     * @param id the value for SYS.ACC_PERMISS.ID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.DESCRIPTION
     *
     * @return the value of SYS.ACC_PERMISS.DESCRIPTION
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.DESCRIPTION
     *
     * @param description the value for SYS.ACC_PERMISS.DESCRIPTION
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.DBPERMISS
     *
     * @return the value of SYS.ACC_PERMISS.DBPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public String getDbpermiss() {
        return dbpermiss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.DBPERMISS
     *
     * @param dbpermiss the value for SYS.ACC_PERMISS.DBPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setDbpermiss(String dbpermiss) {
        this.dbpermiss = dbpermiss == null ? null : dbpermiss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.FCPERMISS
     *
     * @return the value of SYS.ACC_PERMISS.FCPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public String getFcpermiss() {
        return fcpermiss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.FCPERMISS
     *
     * @param fcpermiss the value for SYS.ACC_PERMISS.FCPERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setFcpermiss(String fcpermiss) {
        this.fcpermiss = fcpermiss == null ? null : fcpermiss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.GET_TIME
     *
     * @return the value of SYS.ACC_PERMISS.GET_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.GET_TIME
     *
     * @param getTime the value for SYS.ACC_PERMISS.GET_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.END_TIME
     *
     * @return the value of SYS.ACC_PERMISS.END_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.END_TIME
     *
     * @param endTime the value for SYS.ACC_PERMISS.END_TIME
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.ENABLE
     *
     * @return the value of SYS.ACC_PERMISS.ENABLE
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public Short getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.ENABLE
     *
     * @param enable the value for SYS.ACC_PERMISS.ENABLE
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setEnable(Short enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ACC_PERMISS.PID
     *
     * @return the value of SYS.ACC_PERMISS.PID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ACC_PERMISS.PID
     *
     * @param pid the value for SYS.ACC_PERMISS.PID
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-04 15:38:42
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", powerid=").append(powerid);
        sb.append(", id=").append(id);
        sb.append(", description=").append(description);
        sb.append(", dbpermiss=").append(dbpermiss);
        sb.append(", fcpermiss=").append(fcpermiss);
        sb.append(", getTime=").append(getTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", enable=").append(enable);
        sb.append(", pid=").append(pid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}