package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.PER_INFO
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-07 15:40:00
 */
public class Person implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.ID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.SEX
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.NATION
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.NATIVE_PLACE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.POLITICS_STATUS
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String politicsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.IC_NUMBER
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String icNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.TEL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.EDU_BG
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String eduBg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.ROLE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.BIRTH
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.SCHOOLID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private Short schoolid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.PER_INFO.MAIL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.ID
     *
     * @return the value of SYS.PER_INFO.ID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.ID
     *
     * @param id the value for SYS.PER_INFO.ID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.NAME
     *
     * @return the value of SYS.PER_INFO.NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.NAME
     *
     * @param name the value for SYS.PER_INFO.NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.SEX
     *
     * @return the value of SYS.PER_INFO.SEX
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.SEX
     *
     * @param sex the value for SYS.PER_INFO.SEX
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.NATION
     *
     * @return the value of SYS.PER_INFO.NATION
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.NATION
     *
     * @param nation the value for SYS.PER_INFO.NATION
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.NATIVE_PLACE
     *
     * @return the value of SYS.PER_INFO.NATIVE_PLACE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.NATIVE_PLACE
     *
     * @param nativePlace the value for SYS.PER_INFO.NATIVE_PLACE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.POLITICS_STATUS
     *
     * @return the value of SYS.PER_INFO.POLITICS_STATUS
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getPoliticsStatus() {
        return politicsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.POLITICS_STATUS
     *
     * @param politicsStatus the value for SYS.PER_INFO.POLITICS_STATUS
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus == null ? null : politicsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.IC_NUMBER
     *
     * @return the value of SYS.PER_INFO.IC_NUMBER
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getIcNumber() {
        return icNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.IC_NUMBER
     *
     * @param icNumber the value for SYS.PER_INFO.IC_NUMBER
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setIcNumber(String icNumber) {
        this.icNumber = icNumber == null ? null : icNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.TEL
     *
     * @return the value of SYS.PER_INFO.TEL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.TEL
     *
     * @param tel the value for SYS.PER_INFO.TEL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.EDU_BG
     *
     * @return the value of SYS.PER_INFO.EDU_BG
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getEduBg() {
        return eduBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.EDU_BG
     *
     * @param eduBg the value for SYS.PER_INFO.EDU_BG
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setEduBg(String eduBg) {
        this.eduBg = eduBg == null ? null : eduBg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.ROLE
     *
     * @return the value of SYS.PER_INFO.ROLE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.ROLE
     *
     * @param role the value for SYS.PER_INFO.ROLE
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.SCHOOL_NAME
     *
     * @return the value of SYS.PER_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.SCHOOL_NAME
     *
     * @param schoolName the value for SYS.PER_INFO.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.BIRTH
     *
     * @return the value of SYS.PER_INFO.BIRTH
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.BIRTH
     *
     * @param birth the value for SYS.PER_INFO.BIRTH
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.SCHOOLID
     *
     * @return the value of SYS.PER_INFO.SCHOOLID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public Short getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.SCHOOLID
     *
     * @param schoolid the value for SYS.PER_INFO.SCHOOLID
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setSchoolid(Short schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.PER_INFO.MAIL
     *
     * @return the value of SYS.PER_INFO.MAIL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.PER_INFO.MAIL
     *
     * @param mail the value for SYS.PER_INFO.MAIL
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-09-07 15:40:00
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", nation=").append(nation);
        sb.append(", nativePlace=").append(nativePlace);
        sb.append(", politicsStatus=").append(politicsStatus);
        sb.append(", icNumber=").append(icNumber);
        sb.append(", tel=").append(tel);
        sb.append(", eduBg=").append(eduBg);
        sb.append(", role=").append(role);
        sb.append(", schoolName=").append(schoolName);
        sb.append(", birth=").append(birth);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", mail=").append(mail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}