package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.RES_EDU
 *
 * @mbg.generated do_not_delete_during_merge 2019-08-31 09:33:07
 */
public class ResEdu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.ID_EDU
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Short idEdu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.START_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.END_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.ADDRESS
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.MAJOR
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.EDU_BG
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String eduBg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.RES_EDU.OTHER
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.RES_EDU
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.ID_EDU
     *
     * @return the value of SYS.RES_EDU.ID_EDU
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Short getIdEdu() {
        return idEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.ID_EDU
     *
     * @param idEdu the value for SYS.RES_EDU.ID_EDU
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setIdEdu(Short idEdu) {
        this.idEdu = idEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.ID
     *
     * @return the value of SYS.RES_EDU.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.ID
     *
     * @param id the value for SYS.RES_EDU.ID
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.START_TIME
     *
     * @return the value of SYS.RES_EDU.START_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.START_TIME
     *
     * @param startTime the value for SYS.RES_EDU.START_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.END_TIME
     *
     * @return the value of SYS.RES_EDU.END_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.END_TIME
     *
     * @param endTime the value for SYS.RES_EDU.END_TIME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.ADDRESS
     *
     * @return the value of SYS.RES_EDU.ADDRESS
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.ADDRESS
     *
     * @param address the value for SYS.RES_EDU.ADDRESS
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.MAJOR
     *
     * @return the value of SYS.RES_EDU.MAJOR
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.MAJOR
     *
     * @param major the value for SYS.RES_EDU.MAJOR
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.EDU_BG
     *
     * @return the value of SYS.RES_EDU.EDU_BG
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getEduBg() {
        return eduBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.EDU_BG
     *
     * @param eduBg the value for SYS.RES_EDU.EDU_BG
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setEduBg(String eduBg) {
        this.eduBg = eduBg == null ? null : eduBg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.RES_EDU.OTHER
     *
     * @return the value of SYS.RES_EDU.OTHER
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.RES_EDU.OTHER
     *
     * @param other the value for SYS.RES_EDU.OTHER
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.RES_EDU
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idEdu=").append(idEdu);
        sb.append(", id=").append(id);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", address=").append(address);
        sb.append(", major=").append(major);
        sb.append(", eduBg=").append(eduBg);
        sb.append(", other=").append(other);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}