package com.tew.service;

import com.tew.pojo.Person;
import com.tew.pojo.PersonExample;

import java.util.List;

public interface PersonDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    Person selectByPrimaryKey(String id);


    List<Person> selectByExample(PersonExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.PER_INFO
     *
     * @mbg.generated 2019-08-26 14:21:15
     */
    int updateByPrimaryKey(Person record);
}