package com.tew.dao;

import com.tew.pojo.FileInfo;
import com.tew.pojo.FileInfoExample;
import java.util.List;

public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    List<FileInfo> selectByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    FileInfo selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    int updateByPrimaryKeySelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    int updateByPrimaryKey(FileInfo record);
}