package com.tew.dao;

import com.tew.pojo.Health;
import com.tew.pojo.HealthExample;
import java.util.List;

public interface HealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    int insert(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    int insertSelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    List<Health> selectByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    Health selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    int updateByPrimaryKeySelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.HEA_INFO
     *
     * @mbg.generated 2019-10-01 16:21:29
     */
    int updateByPrimaryKey(Health record);
}