package com.tew.dao;

import com.tew.pojo.School;
import com.tew.pojo.SchoolExample;
import java.util.List;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int deleteByPrimaryKey(Short schoolid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    List<School> selectByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    School selectByPrimaryKey(Short schoolid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.SCH_INFO
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int updateByPrimaryKey(School record);
}