package com.tew.dao;

import com.tew.pojo.Theme;
import com.tew.pojo.ThemeExample;
import java.util.List;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int deleteByPrimaryKey(Short themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    List<Theme> selectByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    Theme selectByPrimaryKey(Short themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int updateByPrimaryKeySelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_THEME
     *
     * @mbg.generated 2019-08-31 09:33:07
     */
    int updateByPrimaryKey(Theme record);
}