package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.FILE_INFO
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-12 13:37:56
 */
public class FileInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.FILE_INFO.ID
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.FILE_INFO.URL
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.FILE_INFO.FILENAME
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.FILE_INFO.DESCRIPTION
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.FILE_INFO.CREATE_AT
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.FILE_INFO.ID
     *
     * @return the value of SYS.FILE_INFO.ID
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.FILE_INFO.ID
     *
     * @param id the value for SYS.FILE_INFO.ID
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.FILE_INFO.URL
     *
     * @return the value of SYS.FILE_INFO.URL
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.FILE_INFO.URL
     *
     * @param url the value for SYS.FILE_INFO.URL
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.FILE_INFO.FILENAME
     *
     * @return the value of SYS.FILE_INFO.FILENAME
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.FILE_INFO.FILENAME
     *
     * @param filename the value for SYS.FILE_INFO.FILENAME
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.FILE_INFO.DESCRIPTION
     *
     * @return the value of SYS.FILE_INFO.DESCRIPTION
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.FILE_INFO.DESCRIPTION
     *
     * @param description the value for SYS.FILE_INFO.DESCRIPTION
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.FILE_INFO.CREATE_AT
     *
     * @return the value of SYS.FILE_INFO.CREATE_AT
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.FILE_INFO.CREATE_AT
     *
     * @param createAt the value for SYS.FILE_INFO.CREATE_AT
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.FILE_INFO
     *
     * @mbg.generated 2019-09-12 13:37:56
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append(", filename=").append(filename);
        sb.append(", description=").append(description);
        sb.append(", createAt=").append(createAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}