package com.tew.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermissExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public PermissExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPoweridIsNull() {
            addCriterion("POWERID is null");
            return (Criteria) this;
        }

        public Criteria andPoweridIsNotNull() {
            addCriterion("POWERID is not null");
            return (Criteria) this;
        }

        public Criteria andPoweridEqualTo(Short value) {
            addCriterion("POWERID =", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridNotEqualTo(Short value) {
            addCriterion("POWERID <>", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridGreaterThan(Short value) {
            addCriterion("POWERID >", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridGreaterThanOrEqualTo(Short value) {
            addCriterion("POWERID >=", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridLessThan(Short value) {
            addCriterion("POWERID <", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridLessThanOrEqualTo(Short value) {
            addCriterion("POWERID <=", value, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridIn(List<Short> values) {
            addCriterion("POWERID in", values, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridNotIn(List<Short> values) {
            addCriterion("POWERID not in", values, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridBetween(Short value1, Short value2) {
            addCriterion("POWERID between", value1, value2, "powerid");
            return (Criteria) this;
        }

        public Criteria andPoweridNotBetween(Short value1, Short value2) {
            addCriterion("POWERID not between", value1, value2, "powerid");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDbpermissIsNull() {
            addCriterion("DBPERMISS is null");
            return (Criteria) this;
        }

        public Criteria andDbpermissIsNotNull() {
            addCriterion("DBPERMISS is not null");
            return (Criteria) this;
        }

        public Criteria andDbpermissEqualTo(String value) {
            addCriterion("DBPERMISS =", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissNotEqualTo(String value) {
            addCriterion("DBPERMISS <>", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissGreaterThan(String value) {
            addCriterion("DBPERMISS >", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissGreaterThanOrEqualTo(String value) {
            addCriterion("DBPERMISS >=", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissLessThan(String value) {
            addCriterion("DBPERMISS <", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissLessThanOrEqualTo(String value) {
            addCriterion("DBPERMISS <=", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissLike(String value) {
            addCriterion("DBPERMISS like", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissNotLike(String value) {
            addCriterion("DBPERMISS not like", value, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissIn(List<String> values) {
            addCriterion("DBPERMISS in", values, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissNotIn(List<String> values) {
            addCriterion("DBPERMISS not in", values, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissBetween(String value1, String value2) {
            addCriterion("DBPERMISS between", value1, value2, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andDbpermissNotBetween(String value1, String value2) {
            addCriterion("DBPERMISS not between", value1, value2, "dbpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissIsNull() {
            addCriterion("FCPERMISS is null");
            return (Criteria) this;
        }

        public Criteria andFcpermissIsNotNull() {
            addCriterion("FCPERMISS is not null");
            return (Criteria) this;
        }

        public Criteria andFcpermissEqualTo(String value) {
            addCriterion("FCPERMISS =", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissNotEqualTo(String value) {
            addCriterion("FCPERMISS <>", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissGreaterThan(String value) {
            addCriterion("FCPERMISS >", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissGreaterThanOrEqualTo(String value) {
            addCriterion("FCPERMISS >=", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissLessThan(String value) {
            addCriterion("FCPERMISS <", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissLessThanOrEqualTo(String value) {
            addCriterion("FCPERMISS <=", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissLike(String value) {
            addCriterion("FCPERMISS like", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissNotLike(String value) {
            addCriterion("FCPERMISS not like", value, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissIn(List<String> values) {
            addCriterion("FCPERMISS in", values, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissNotIn(List<String> values) {
            addCriterion("FCPERMISS not in", values, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissBetween(String value1, String value2) {
            addCriterion("FCPERMISS between", value1, value2, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andFcpermissNotBetween(String value1, String value2) {
            addCriterion("FCPERMISS not between", value1, value2, "fcpermiss");
            return (Criteria) this;
        }

        public Criteria andGetTimeIsNull() {
            addCriterion("GET_TIME is null");
            return (Criteria) this;
        }

        public Criteria andGetTimeIsNotNull() {
            addCriterion("GET_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andGetTimeEqualTo(Date value) {
            addCriterion("GET_TIME =", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotEqualTo(Date value) {
            addCriterion("GET_TIME <>", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeGreaterThan(Date value) {
            addCriterion("GET_TIME >", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("GET_TIME >=", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeLessThan(Date value) {
            addCriterion("GET_TIME <", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeLessThanOrEqualTo(Date value) {
            addCriterion("GET_TIME <=", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeIn(List<Date> values) {
            addCriterion("GET_TIME in", values, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotIn(List<Date> values) {
            addCriterion("GET_TIME not in", values, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeBetween(Date value1, Date value2) {
            addCriterion("GET_TIME between", value1, value2, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotBetween(Date value1, Date value2) {
            addCriterion("GET_TIME not between", value1, value2, "getTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Short value) {
            addCriterion("ENABLE =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Short value) {
            addCriterion("ENABLE <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Short value) {
            addCriterion("ENABLE >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Short value) {
            addCriterion("ENABLE >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Short value) {
            addCriterion("ENABLE <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Short value) {
            addCriterion("ENABLE <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Short> values) {
            addCriterion("ENABLE in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Short> values) {
            addCriterion("ENABLE not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Short value1, Short value2) {
            addCriterion("ENABLE between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Short value1, Short value2) {
            addCriterion("ENABLE not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("PID is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("PID is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("PID =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("PID <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("PID >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("PID >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("PID <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("PID <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("PID like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("PID not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("PID in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("PID not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("PID between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("PID not between", value1, value2, "pid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated do_not_delete_during_merge 2019-11-02 18:57:03
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.ACC_PERMISS
     *
     * @mbg.generated 2019-11-02 18:57:03
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}