package com.tew.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYS.INV_SCHOOL
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-02 18:56:40
 */
public class SchoolJob implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.SCHOOL_THE_JOBID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Short schoolTheJobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.THEMEID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Short themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.POST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.NUM
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Short num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.CREATE_AT
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.REQUEST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private String request;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.SCHOOLID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Short schoolid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.CLAZZ
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.INV_SCHOOL.ENABLE
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private Short enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.INV_SCHOOL
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.SCHOOL_THE_JOBID
     *
     * @return the value of SYS.INV_SCHOOL.SCHOOL_THE_JOBID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Short getSchoolTheJobid() {
        return schoolTheJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.SCHOOL_THE_JOBID
     *
     * @param schoolTheJobid the value for SYS.INV_SCHOOL.SCHOOL_THE_JOBID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setSchoolTheJobid(Short schoolTheJobid) {
        this.schoolTheJobid = schoolTheJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.THEMEID
     *
     * @return the value of SYS.INV_SCHOOL.THEMEID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Short getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.THEMEID
     *
     * @param themeid the value for SYS.INV_SCHOOL.THEMEID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setThemeid(Short themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.POST
     *
     * @return the value of SYS.INV_SCHOOL.POST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.POST
     *
     * @param post the value for SYS.INV_SCHOOL.POST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.NUM
     *
     * @return the value of SYS.INV_SCHOOL.NUM
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.NUM
     *
     * @param num the value for SYS.INV_SCHOOL.NUM
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.CREATE_AT
     *
     * @return the value of SYS.INV_SCHOOL.CREATE_AT
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.CREATE_AT
     *
     * @param createAt the value for SYS.INV_SCHOOL.CREATE_AT
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.REQUEST
     *
     * @return the value of SYS.INV_SCHOOL.REQUEST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.REQUEST
     *
     * @param request the value for SYS.INV_SCHOOL.REQUEST
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.SCHOOLID
     *
     * @return the value of SYS.INV_SCHOOL.SCHOOLID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Short getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.SCHOOLID
     *
     * @param schoolid the value for SYS.INV_SCHOOL.SCHOOLID
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setSchoolid(Short schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.SCHOOL_NAME
     *
     * @return the value of SYS.INV_SCHOOL.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.SCHOOL_NAME
     *
     * @param schoolName the value for SYS.INV_SCHOOL.SCHOOL_NAME
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.CLAZZ
     *
     * @return the value of SYS.INV_SCHOOL.CLAZZ
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.CLAZZ
     *
     * @param clazz the value for SYS.INV_SCHOOL.CLAZZ
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.INV_SCHOOL.ENABLE
     *
     * @return the value of SYS.INV_SCHOOL.ENABLE
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public Short getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.INV_SCHOOL.ENABLE
     *
     * @param enable the value for SYS.INV_SCHOOL.ENABLE
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    public void setEnable(Short enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.INV_SCHOOL
     *
     * @mbg.generated 2019-09-02 18:56:40
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schoolTheJobid=").append(schoolTheJobid);
        sb.append(", themeid=").append(themeid);
        sb.append(", post=").append(post);
        sb.append(", num=").append(num);
        sb.append(", createAt=").append(createAt);
        sb.append(", request=").append(request);
        sb.append(", schoolid=").append(schoolid);
        sb.append(", schoolName=").append(schoolName);
        sb.append(", clazz=").append(clazz);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}